language: java

jdk:
  - openjdk8
  - openjdk9
  - openjdk11
  - openjdk13
#  - openjdk14

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Upload log to S3
# https://docs.travis-ci.com/user/uploading-artifacts/
addons:
  artifacts:
    paths:
      - ./log.txt