dist: bionic # Ubuntu 18.04 (Bionic Beaver)

language: java

jdk:
  - openjdk8
  - openjdk9
  - openjdk11
#  - openjdk13
  - openjdk14

env:
  - ORG_GRADLE_PROJECT_kafkaVersion=1.0.0
  - ORG_GRADLE_PROJECT_kafkaVersion=1.1.1
#  - ORG_GRADLE_PROJECT_kafkaVersion=2.0.0
  - ORG_GRADLE_PROJECT_kafkaVersion=2.2.2
  - ORG_GRADLE_PROJECT_kafkaVersion=2.3.1
#  - ORG_GRADLE_PROJECT_kafkaVersion=2.4.1
  - ORG_GRADLE_PROJECT_kafkaVersion=2.5.0

#jobs:
#  exclude:
#    - jdk: openjdk8
#      env: ORG_GRADLE_PROJECT_kafkaVersion=2.4.1
#    - jdk: openjdk9
#      env: ORG_GRADLE_PROJECT_kafkaVersion=2.4.1

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Upload log to S3
# https://docs.travis-ci.com/user/uploading-artifacts/
addons:
  artifacts:
    paths:
      - ./log.txt